<a href="https://colab.research.google.com/github/andrew-wairegi-school/week-3-ip/blob/main/Moringa_Data_Science_Prep_W3_Independent_Project_2021_09_Andrew_Wairegi_Python_Notebook_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# link to github repository for project: https://github.com/andrew-wairegi-school/week-3-ip

### Importing the libraries

In [3]:
import numpy as np
import pandas as pd

### Loading the data

#### Data Datasets

In [4]:
# Cells location
url = "https://drive.google.com/uc?id=1Js3pa2fCPxEeWwrZsK2h_UD95uuiqttF"
cell_location_df = pd.read_csv(url, delimiter = ";")
cell_location_df = cell_location_df.drop(labels = "Unnamed: 0", axis = 1)
cell_location_df.head(2)

   VILLES      STATUS LOCALISATION  ... AREA     CELL_ID   SITE_CODE
0  ADJAME  In Service      ABIDJAN  ...  NaN  fbb2e75af3  0bb492ef17
1  ADJAME  In Service      ABIDJAN  ...  NaN  1502501d78  0bb492ef17

[2 rows x 11 columns]

In [5]:
# Cellphone information tables
# Day 1 - 2012 05 06
url = "https://drive.google.com/uc?id=1R6Iu_6C2O3QHDyGiHITNFLVgKtVt14pR"
info_df = pd.read_csv(url)
info_df.head(2)

  PRODUTC  VALUE               DATETIME  ... COUNTRY_B     CELL_ID     SITE_ID
0   Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1     sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41

[2 rows x 10 columns]

In [6]:
# Day 2 - 2012 05 07 
url = "https://drive.google.com/uc?id=1ynkmD2dlOsk3r7Want9vJfEHIrP-iiAs"
info_df2 = pd.read_csv(url)
info_df2.head(2)

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0     sms      0  2012-05-07 23:02:06.0  ...     19e2e  +854AcBQT2  +854AcBQT2
1   Voice      0  2012-05-07 23:03:44.0  ...     19e2e  +854AcBQT2  +854AcBQT2

[2 rows x 10 columns]

In [7]:
# Day 3 - 2012 05 08
url = "https://drive.google.com/uc?id=1YjCu_5DJBUOV9xwDaMimVdk_jyOFWbSN"
info_df3 = pd.read_csv(url)
info_df3.head(2)

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B      CELLID     SIET_ID
0   Voice     61  2012-05-08 23:01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1     sms      0  2012-05-08 23:01:31.0  ...     19e2e  +Fs4mTvdKx  +Fs4mTvdKx

[2 rows x 10 columns]

#### Description Datasets

In [8]:
# Cells dataset descriptions
url = "https://drive.google.com/uc?id=1lZbKs4vtnw2khGQf11twPcR1e_e6DbZF"
cells_description = pd.read_excel(url, sheet_name = 0)
cells_description.head(1)

  Column name Description  Format
0      VILLES        City  String

In [9]:
# Cellphone record dataset descriptions
url = "https://drive.google.com/uc?id=1sENgvhV_AbOJhD4FPX2zJmfDJFf5srH-"
cellphones_description = pd.read_excel(url, sheet_name = 0)
cellphones_description.head(1)

  Column name   Description  Format
0     PRODUCT  Voice or SMS  String

### Exploration

There seems to be an error with the column names. So we need to fix that first

In [10]:
info_df.columns = info_df2.columns
info_df3.columns = info_df2.columns

In [11]:
info_df.head(3)

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0   Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1     sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2     sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi

[3 rows x 10 columns]

In [12]:
info_df2.head(3)

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0     sms      0  2012-05-07 23:02:06.0  ...     19e2e  +854AcBQT2  +854AcBQT2
1   Voice      0  2012-05-07 23:03:44.0  ...     19e2e  +854AcBQT2  +854AcBQT2
2     sms      0  2012-05-07 23:04:06.0  ...     19e2e  +laSrk7g6q  +laSrk7g6q

[3 rows x 10 columns]

In [13]:
info_df3.head(3)

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0   Voice     61  2012-05-08 23:01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1     sms      0  2012-05-08 23:01:31.0  ...     19e2e  +Fs4mTvdKx  +Fs4mTvdKx
2   Voice     10  2012-05-08 23:02:59.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+

[3 rows x 10 columns]

They all look ok now

Exploration

In [14]:
info_df2["COUNTRY_B"].unique()

array(['19e2e', 'OTHER'], dtype=object)

It appears to be that there is only one country B

In [15]:
info_df2["COUNTRY_A"].unique()

array(['19e2e'], dtype=object)

There also appears to be only one country A in the dataset,
and they are both the same. Which means that we must be only viewing data
For MTN within the same country, Cote D'Ivoire

In [16]:
info_df3["COUNTRY_A"].unique()

array(['19e2e'], dtype=object)

This is also the same. For the other datasets. So the datasets only contain information for telecommunication within Cote D'Ivoire.

Let's see the description dataset. For the cellphone information datasets

In [17]:
cellphones_description

       Column name                                        Description   Format
0          PRODUCT                                       Voice or SMS   String
1            VALUE                                      Billing price  Integer
2        DATE_TIME               Time in format yyyy-MM-dd hh:mm:ss.0   String
3     CELL_ON_SITE  Which cell in the site was used (not needed here)  Integer
4  DW_A_NUMBER_INT  Anonymized phone number of the person for whic...   String
5  DW_B_NUMBER_INT        Anonymized phone number of the counterparty   String
6        COUNTRY_A                  Country of party A (useless here)   String
7        COUNTRY_B                  Country of party B (useless here)   String
8          CELL_ID                                     ID of the cell   String
9          SITE_ID                                     ID of the SITE   String

The table above says that we are only looking at Voice or SMS data.
The billing price is also available. As well as the Cell being used.
The site ID is also available. Which is most probably the location of the user.
In an compressed manner

Let's look at the cell description dataset

In [18]:
cells_description

     Column name                                        Description  Format
0         VILLES                                               City  String
1         STATUS                                  In Service or not  String
2   LOCALISATION                                  in ABIDJAN or not  String
3     DECOUPZONE                                  Geographical Zone  String
4       ZONENAME                                       Name of Zone  String
5      LONGITUDE                                          Longitude   Float
6       LATITUDE                                           Latitude   Float
7         REGION                                             Region  String
8           AREA                                               Area  String
9        CELL_ID                                     ID of the cell  String
10     SITE_CODE  Site (there are several cells per site, severa...  String

We have different information. About the cell's location of different cells. This will be usefull in analysis. When we are trying to determine which locations. Should have more cells.

Let's look at the cellphone info datasets. For one day

In [19]:
info_df

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0      Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1        sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2        sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3      Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4      Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
...      ...    ...                    ...  ...       ...         ...         ...
4996     sms    100  2012-05-07 00:01:54.0  ...     OTHER  0c2371d9bc  1e751d08a4
4997   Voice      1  2012-05-07 00:01:54.0  ...     19e2e  5fb791cf56  65efe2bc62
4998   Voice      0  2012-05-07 00:01:54.0  ...     19e2e  7773627c12  9ef9616350
4999   Voice      0  2012-05-07 00:01:54.0  ...     19e2e  3f4af49d6c  969b8d0e39
5000   Voice      7  2012-05-07 00:01:54.0  ...     19e2e  6f4d9b77a5  ebfc58af70

[5001 rows x 10 columns]

Let's look at the cell dataset

In [20]:
cell_location_df

        VILLES      STATUS LOCALISATION  ...          AREA     CELL_ID   SITE_CODE
0       ADJAME  In Service      ABIDJAN  ...           NaN  fbb2e75af3  0bb492ef17
1       ADJAME  In Service      ABIDJAN  ...           NaN  1502501d78  0bb492ef17
2       ADJAME  In Service      ABIDJAN  ...           NaN  0c2e182a0c  0bb492ef17
3      ASSINIE  In Service    INTERIEUR  ...           NaN  69bdfc69fd  8a1e6ce31f
4      ASSINIE  In Service    INTERIEUR  ...           NaN  7a1029d2ab  8a1e6ce31f
...        ...         ...          ...  ...           ...         ...         ...
3969  ZUENOULA  In Service    INTERIEUR  ...  CENTRE NORTH  1cfc2d7ab1  f91ed8d2e9
3970  ZUENOULA  In Service    INTERIEUR  ...  CENTRE NORTH  3ae1708153  f91ed8d2e9
3971  ZUENOULA  In Service    INTERIEUR  ...  CENTRE NORTH  cb71f8a29c  61bee9c70c
3972  ZUENOULA  In Service    INTERIEUR  ...  CENTRE NORTH  d4a6a0b645  61bee9c70c
3973  ZUENOULA  In Service    INTERIEUR  ...  CENTRE NORTH  f9f3e42589  61bee9c70c

[3974 rows x 11 columns]

In [21]:
cell_location_df["DECOUPZONE"].unique()

array(['"Abidjan_EST', 'Grand-EST', 'Grand-OUEST', '"Abidjan_NORD',
       '"Abidjan_CENTRE', 'Abidjan_NORD', 'Abidjan_EST', 'Abidjan_OUEST',
       'Grand-SUD', 'SUD-OUEST', 'Abidjan_CENTRE', 'Abidjan_SUD',
       'Grand-NORD', 'Gd-ABIDJAN', '0'], dtype=object)

There are a lot of DecoupZones. But they are only about Abidjan.
It looks like ZoneName would be more usefull to us.

In [22]:
cell_location_df["REGION"].unique()

array(['LAGUNE', 'SUD COMOE', 'HAUT SASSANDRA', 'MOYEN COMOE', 'AGNEBY',
       'SUD BANDAMA', 'BAS SASSANDRA', 'LACS', 'FROMAGER',
       'VALLEE DU BANDAMA', 'NZI COMOE', 'ZANZAN', 'MOYEN CAVALLY',
       'WORODOUGOU', 'DENGUELE', '18 MONTAGNES', 'SAVANE', 'MARAHOUE',
       'BAFING'], dtype=object)

These are much more. We will be able to use them. When trying to identify
where cells should be placed.

### Cleaning

1. We need to convert the column names to lowercase.
So they're easier to use

In [23]:
info_df.columns = map(str.lower, info_df.columns)

In [24]:
info_df.columns

Index(['product', 'value', 'date_time', 'cell_on_site', 'dw_a_number',
       'dw_b_number', 'country_a', 'country_b', 'cell_id', 'site_id'],
      dtype='object')

In [25]:
info_df2.columns = map(str.lower, info_df2.columns)

In [26]:
info_df3.columns = map(str.lower, info_df3.columns)

In [27]:
cell_location_df.columns = map(str.lower, cell_location_df.columns)

In [28]:
cell_location_df.columns

Index(['villes', 'status', 'localisation', 'decoupzone', 'zonename',
       'longitude', 'latitude', 'region', 'area', 'cell_id', 'site_code'],
      dtype='object')

2. Clean out the missing values in each dataset

In [29]:
info_df.isnull().sum()

product           0
value             0
date_time         0
cell_on_site      0
dw_a_number       0
dw_b_number       0
country_a         0
country_b         0
cell_id           0
site_id         716
dtype: int64

In [30]:
info_df2.isnull().sum()

product           0
value             0
date_time         0
cell_on_site      0
dw_a_number       0
dw_b_number       0
country_a         0
country_b         0
cell_id           0
site_id         676
dtype: int64

In [31]:
info_df3.isnull().sum()

product           0
value             0
date_time         0
cell_on_site      0
dw_a_number       0
dw_b_number       0
country_a         0
country_b         0
cell_id           0
site_id         605
dtype: int64

It appears that site_id is the only column that is missing values from the dataframe. Since we don't need it for analysis, we can just drop that column from each of the datasets.

In [32]:
info_df.drop(["site_id"], axis = 1, inplace = True)
info_df2.drop(["site_id"], axis = 1, inplace = True)
info_df3.drop(["site_id"], axis = 1, inplace = True)

In [33]:
info_df

     product  value              date_time  ... country_a country_b     cell_id
0      Voice      0  2012-05-06 23:04:37.0  ...     19e2e     19e2e  /TJNe+Mmtu
1        sms      0  2012-05-06 23:05:25.0  ...     19e2e     19e2e  /+cKZKIp41
2        sms     25  2012-05-06 23:05:41.0  ...     19e2e     19e2e  /u0FSD+ahi
3      Voice     56  2012-05-06 23:05:42.0  ...     19e2e     19e2e  +cNeJzsTp3
4      Voice     14  2012-05-06 23:06:29.0  ...     19e2e     19e2e  051KhYDCpv
...      ...    ...                    ...  ...       ...       ...         ...
4996     sms    100  2012-05-07 00:01:54.0  ...     19e2e     OTHER  0c2371d9bc
4997   Voice      1  2012-05-07 00:01:54.0  ...     19e2e     19e2e  5fb791cf56
4998   Voice      0  2012-05-07 00:01:54.0  ...     19e2e     19e2e  7773627c12
4999   Voice      0  2012-05-07 00:01:54.0  ...     19e2e     19e2e  3f4af49d6c
5000   Voice      7  2012-05-07 00:01:54.0  ...     19e2e     19e2e  6f4d9b77a5

[5001 rows x 9 columns]

In [34]:
info_df.isnull().sum()

product         0
value           0
date_time       0
cell_on_site    0
dw_a_number     0
dw_b_number     0
country_a       0
country_b       0
cell_id         0
dtype: int64

In [35]:
cell_location_df.isnull().sum()

villes           0
status          67
localisation     0
decoupzone       0
zonename         6
longitude        0
latitude         0
region           0
area            23
cell_id          0
site_code        0
dtype: int64

Since we might need to identify these cells. It may be better not to drop them.

3. We need to check for duplicates

In [36]:
info_df.duplicated().sum()

82

In [37]:
info_df2.duplicated().sum()

78

In [38]:
info_df3.duplicated().sum()

93

In [39]:
# Drop duplicates
info_df.drop_duplicates(inplace = True)
info_df2.drop_duplicates(inplace = True)
info_df3.drop_duplicates(inplace = True)

In [40]:
info_df.duplicated().sum()

0

In [41]:
# Let's check for the cell dataframe

In [42]:
cell_location_df.duplicated().sum()

43

In [43]:
# Drop duplicates
cell_location_df.drop_duplicates(inplace = True)

In [44]:
cell_location_df.duplicated().sum()

0

4. We need to join the tables. Incase we need them for analysis.

In [45]:
info_df_all = pd.concat([info_df, info_df2, info_df3], axis = 0)
info_df_all

     product  value              date_time  ... country_a country_b     cell_id
0      Voice      0  2012-05-06 23:04:37.0  ...     19e2e     19e2e  /TJNe+Mmtu
1        sms      0  2012-05-06 23:05:25.0  ...     19e2e     19e2e  /+cKZKIp41
2        sms     25  2012-05-06 23:05:41.0  ...     19e2e     19e2e  /u0FSD+ahi
3      Voice     56  2012-05-06 23:05:42.0  ...     19e2e     19e2e  +cNeJzsTp3
4      Voice     14  2012-05-06 23:06:29.0  ...     19e2e     19e2e  051KhYDCpv
...      ...    ...                    ...  ...       ...       ...         ...
4995   Voice     10  2012-05-09 00:01:43.0  ...     19e2e     OTHER  6467daa1db
4996   Voice      0  2012-05-09 00:01:43.0  ...     19e2e     19e2e  2aa04dcab7
4997   Voice     62  2012-05-09 00:01:43.0  ...     19e2e     19e2e  7f1f2f889f
4999   Voice     30  2012-05-09 00:01:43.0  ...     19e2e     19e2e  98ed726da2
5000   Voice     60  2012-05-09 00:01:43.0  ...     19e2e     19e2e  1c11a2fcbb

[14750 rows x 9 columns]

### Analysis of Data

In [46]:
cell_location_df["cell_id"].unique()

array(['fbb2e75af3', '1502501d78', '0c2e182a0c', ..., 'cb71f8a29c',
       'd4a6a0b645', 'f9f3e42589'], dtype=object)

In [47]:
info_df_all["cell_id"].unique()

array(['/TJNe+Mmtu', '/+cKZKIp41', '/u0FSD+ahi', ..., 'd5bdd4f4cb',
       '425d28ede5', '6467daa1db'], dtype=object)

In [48]:
cell_location_df["cell_id"].isin(info_df_all["cell_id"].unique()).sum()

0

It appears that none of the Cell Id's from the cell user column. Are in the cell location column. So we will just have to recommend ID's from the Cell users table.

Hopefully, MTN will be able to know these cell tower locations. As well as know which locations to prefer over the others.

In [49]:
info_df_all["cell_id"].value_counts()

ffa6759bb2    1960
03ee801971      73
cc7ce19d6b      65
b78724d6fc      42
d22224b2fa      40
              ...
0db5926358       1
772a0a9b50       1
97e21f3590       1
22f16c5505       1
b8b7f701ef       1
Name: cell_id, Length: 2677, dtype: int64

It appears that they're are multiple ID's of the cells. This means that they are most likely cell tower ID's. Meaning they do not correlate to the user's cellphone ID

In [50]:
cell_ids_group = info_df_all[["value", "cell_id"]].groupby("cell_id")
cell_ids_values = (cell_ids_group.sum()).sort_values(by = "value", ascending = False)

with pd.option_context('display.max_rows', None, 'display.max_columns', None):
  print(cell_ids_values)

            value
cell_id
ffa6759bb2  15284
2def69183e  12900
3f5ac97214   6800
MpOhP3OKNN   4225
5a7f6cf0fa   3437
0cbdf715d0   2772
f1d92c97f9   2528
13c129b7fa   2330
c68a1b9da4   2269
6f3a2df445   2016
89b82605a0   1823
19c95a8eca   1780
47yB6si0R9   1683
c52b9b991c   1620
88a4a4b31b   1584
EpCRhkGWMS   1572
b6e04708a4   1453
6fddc7c18f   1435
07ed226112   1288
d22224b2fa   1281
cd828df0e4   1265
f46ae9694b   1207
6be1ab2849   1186
a9cf96eff4   1121
e73439a17f   1118
68791ae38d   1110
6bd1f7c8b9   1107
3c9bd2ca37   1082
6f5dfedfd3   1073
7ea7f9e5ec   1055
e0ae495f2e   1052
c4f4063607   1042
00404e0105   1007
2975ab6981    990
34f124cb0d    984
765d191617    976
ab68996d93    956
152d6ee99d    930
34f224db6b    925
0f8d8129ca    920
ce18251d3a    913
7475af0010    907
9cfc878d60    894
96a685fc17    877
cb25310346    867
32b36c0459    853
5482031762    848
006b8ebb98    839
d7cb25d4f4    839
2ce3fe25aa    791
706d8914d0    789
885037e317    786
687f868757    785
16ef81d211    784
f426b1653c    784
b7d5388b0c    782
034e373b45    780
577dd249c0    757
9hl3yLvU6j    748
4R4MmPUDw/    746
6sY4KEpEo1    734
7a31902854    734
bc1d885e30    733
4db0540b25    729
876704aa20    725
f9c34a3e8f    723
FDcS1VE6Ua    711
bcc3209833    687
b42d04b0d7    687
7af7f866c8    679
81ce9eeade    675
94438769e6    671
e5e1285933    662
ef70015139    651
4abcf1006e    641
da5894d6b5    640
6f4d9b77a5    638
de92883668    634
afefb687c9    633
d64d369ec1    625
22656c8413    621
c497f58c1d    610
d04adb67fe    607
d250ec4e98    602
5eb266f671    602
6e9f56b3df    601
76ecfdaa75    601
833c2b967a    595
5135db7654    589
a5a96c0e40    585
184ecfcdf9    582
afe06de946    580
05813ba0f9    574
cf0d211307    571
085e63acc5    570
fdfe4e8c70    560
14407a3d56    556
f94a8ed5d0    549
e3b64da2f8    548
96987d95ff    548
6f19884dcb    545
4aece7d310    544
c2bb42ad2c    544
c88ed23334    540
c6b320947f    531
2f50f519d6    528
3f4af49d6c    527
03ee801971    526
MWrzNIudIF    525
35ea965ae6    525
f45dfc1cf6    522
96593c24dd    520
b67ec11806    520
dd98a379f0    520
a4b04a5dc5    514
8b4f82a66a    514
904a4d8fe6    513
7ad3fe32b6    513
f4aceab2e2    513
be04d38f70    512
CKHNgn/WlC    510
ee2e5d5b15    501
79d018a613    500
0a27eecceb    500
0a01c94258    495
0518fc8d4e    489
ea23bd588b    489
7733b8a6cb    488
09ff06d633    483
e19067447c    482
dd11e50b5d    481
f8f987f764    478
25b28c826b    477
4b216dac9b    476
69ade9d187    475
0c2371d9bc    475
a9fac0c585    472
ef7d7f4e3b    471
4831882322    468
9cbb4331fe    466
a1a74bdf01    466
cb7521ac5d    463
ec90c83fd3    461
3d4d3c958b    460
5cdcc07243    459
0Fmr/IZtQ+    458
7ce0e70ac0    454
485ef0de75    454
5c7dc2f617    452
359b6f241a    450
4db5de545c    450
bbcc177399    449
3464b417d5    448
5aa4e8eff6    448
bebf38d432    446
a474356a3c    441
2e93a4410e    440
6db6c89244    439
18aeb675b9    436
665da1dd41    434
00a55603d4    433
7b43d3cd70    422
c7742dcaf9    422
e3bb47093c    421
385e06ef74    420
4f64e93674    418
176sGHv7Ym    416
a78717d203    416
a0e843ee3a    416
fa8a209780    414
5fb791cf56    413
1d068e7a63    413
f3aa9e7eb8    411
2ba685dd7c    411
9d09fa15ee    409
e6d1a0e5b1    408
81ba0da66d    407
b6ef90bf41    407
67bdf5aa5e    403
0a5355b362    403
b86ea70405    402
985a02d2d5    402
3IoIGy1+o8    401
/xvRrCVKoQ    401
18ba0c44e5    401
dc27a3f9d9    400
50770231fb    399
16e65def09    397
b9146a7f83    396
926a847e28    396
64138404ce    395
c537b81993    395
a602f6eb94    394
a394529de6    393
7145abb928    393
75129a301e    390
62d0341dfd    390
3298cdcb7c    389
52be6e498e    389
d1889b433b    388
4390c25c6c    387
188cb3f1c5    386
1cb2f2c1be    384
35ff11e433    383
069b659109    381
b1adfda1f4    380
5d9e63befc    378
a266219184    377
4a7047f1ba    376
1bbd2d834d    375
2cj/HbqLAV    374
c2d02bef86    373
74ffac08d2    372
729b6b4b22    370
fc1efeea69    368
5f8ff28ff9    368
28ef6c4ef2    366
e3ef47df3f    365
3e2287dc73    362
2010dd314d    361
0052aee4c6    360
BpeMWVWM1z    360
264922a1aa    359
eb27f32e7e    358
31ae4582de    358
dec5b1f3c4    357
f907585c1f    355
1a7c017628    354
0b3d50be80    354
5139351fad    354
JwyI40HRU1    353
da3bdb03a1    350
0c40b2e1aa    349
4eddd761b8    348
FiSHrmEwXi    348
9c5f006a36    348
46b9480a4b    347
9bd8a02f7d    346
8cee3d86a3    346
da96896341    345
46007ed334    344
906q8kzUoO    343
OXQ35zAvdd    339
a6606f4ac1    338
0BRdojv2my    336
611ffe7b03    336
cc50ee0fc9    335
99586d686c    333
5d1cc59463    331
7f1f2f889f    331
08beca90e6    331
6572443a4a    330
34ac6e4be2    329
baa72a53a9    328
5f056fdcc9    327
ae3c1f202a    326
0fd7c01716    325
9d8469bfb0    324
88c34bb286    324
d88c900d78    323
a4cf96c756    322
f54e480df9    321
ae4db80773    320
e48b86aa11    319
dbbd77fbe5    318
9l97s9YtkD    318
ce13ed29dd    316
4261f660ef    314
72892aad87    314
1AX75JmPtt    313
1e78f22c1f    313
833e19d1bf    313
805cb43a1e    313
3ac5beb8f8    313
1e5b71aee6    312
04684ebe35    312
bcc73a3107    311
60339d459f    311
40+2aJ4uAc    311
2be4a448fa    311
6hDV1hwf/K    310
a8c1a2f1a7    309
Co2R4AZ8Ux    308
240c589af9    307
bfec9afdba    307
be6853dbcc    306
MQDCR2VlNt    305
6381c01996    305
9C2kuGliRa    305
5475c0798b    305
53304e0ed5    304
d970dcfc39    301
294c5de37f    300
94bd3b3fa0    300
e7f1ba9b42    300
9/CstAxGD8    300
e2ff2bee78    298
11d236748c    298
ad1dac778c    297
554d566c19    296
d3877ceeca    295
d03cc00eff    295
f053be2418    294
06cd7ac7ac    294
92c149d0eb    294
03aed941ac    294
8ecda1b7c9    294
5afc60affb    293
204188bc24    292
8359231c1e    290
0d503d1a0f    290
857b559354    290
5fd5eae55a    289
1ef606a198    288
4b39f70b40    288
4a4160c38b    287
4wcFwPWjZJ    287
593ccf9394    287
0ff4f68649    287
45ff222219    286
54Pb8dz/52    286
MmwcRvyLoz    286
e24c45e260    286
7092e26920    284
6e539305be    283
01743e1656    283
e22b44de5a    282
9ede6af1ec    280
10177c8ebb    280
217ea0f321    280
3003be076c    279
c3a6d994b3    278
0dae2b02f5    278
9a224d3091    275
P9TAf6NBg/    274
4dbcc9cc61    274
a18d0953df    273
1FvEkI2KCW    273
db13b7dfd7    273
88425d57f4    273
147b10ebce    273
843802f48a    272
87835d271a    272
9f3f4322cf    272
14f72fc8bd    272
2106de3c9c    271
fb2d5cd3ff    271
5bcb7ce6d0    270
ecaf33031e    270
c6048ee617    268
c92be6915d    268
26c3cc23da    267
1074ac4397    266
47c741b294    266
8c53301bbc    266
224e99f9b3    265
7e38b2813d    265
629f49257b    265
a57c0c8f99    265
2d722cd43e    264
d0b9055142    264
6b749a3b0f    264
f2e32659be    262
8b9e2007de    262
a4baf2ff7f    260
fbb5df5f5b    259
dd95d1453e    259
067f89441f    259
782734e9c4    258
adf94c6224    258
93mO70RgHR    256
a5e351b2b3    256
117024cabb    256
2d5e6a3639    255
57ffe34d97    255
614cefa84a    254
0a2c94daef    253
ae00876856    252
0bb30f4eb8    252
08a1ad959b    251
df60172f8b    251
5935c85c67    250
45c89352d5    250
4hqZ6VS+Pe    250
771430a49a    250
4cb70ebae5    250
5116d1c4a6    249
7b724c1162    248
7e27ea53d1    248
+38u2u/rfx    247
6e076bfd9c    247
37144b64f7    246
69aa8d0f17    244
22Z3fM8uPX    244
eb962cac28    243
52b8cb68f9    242
7773627c12    241
0eafb3bbcb    241
4e45b06e26    241
35a513722e    241
9525c456e2    240
80c2221eec    240
fc28d26e2d    240
8930ae7091    240
58b411df48    239
d13913a3ed    239
015056c705    239
246f20e1c4    238
72aaa2d181    238
d229a95c9c    238
388e117cc3    238
f892fac747    237
0mXwALOFFi    237
83c10771d1    236
3e80a033dc    235
ba191070ea    235
051KhYDCpv    235
3f5d502beb    234
d01091f9ca    232
1fa9764696    231
7OeLONGBwT    231
7568c25ea2    231
1e1eff45a0    231
0r4EVaG2A/    230
f9639af5ac    229
1cb9f669ee    228
7317c6d69f    228
9f2025bbed    227
8052d4a842    227
b6c065bdb0    227
d13adda2d8    227
14bedd66a9    226
7fdf97e907    225
59250bf63d    225
a962ed39a8    225
977914b97e    225
878554a5dd    225
7d4e715055    224
87ec07b361    224
abcf74be80    224
e0532725f2    223
69336a3e84    223
a1c109351b    223
333a141d84    223
87cef82479    223
5b975beadf    223
5d9dc897f7    223
367312dffd    222
f7cc1c1666    222
245c49061f    221
9181f79f28    221
0331bbdd39    221
2jd/9pF2su    221
2e540c7097    220
28984b3b07    220
13O1+JEun3    219
c919baf9c8    219
29106fd268    218
e28d098535    217
313840c4b9    217
5f4a816311    217
ca5e8248f0    216
315bcd4c33    216
50e0338089    216
8418cc64dd    216
68c5f1ff40    216
dc267159be    216
8630058aca    216
7vwqp+zGUZ    215
e7df6f69ac    214
c56398a6e0    214
000e75b960    213
9f847444ba    212
e21c9c8e36    212
7852975f3d    212
61b4ddc3a2    211
90ad2ba1e9    210
3gJPHLhVkO    210
fc0f9a8be7    209
6e59ea5572    209
Ji5RBowwOF    209
4c8309ed11    208
ea7af6d326    208
3c5b7b0f2a    207
Rl7N0IeohN    206
93d38fc386    206
3a39e7ade4    205
746d16590f    205
f15af24b8b    205
92a4a0642c    205
32fcb79772    204
11f25068ae    203
8bea4b4e6c    203
FEM6ZufS6y    202
1fae208227    202
038b1c178e    200
MDLPbmxPPM    200
b615bf7192    200
202b0eee1e    200
0e1fda2366    200
1640acfc47    200
f582c72524    200
8b5b36f20c    200
3425310c4f    200
c7118d46c9    200
a3ae0a9074    200
4506CmswTv    199
fc91429329    199
0496f0bf97    198
4d44e57552    198
058e42d1ae    198
a7dff74777    197
1a1886282d    196
2901cbe78c    196
3f78767b3e    196
83ce916c3e    196
a2d35deb78    195
3yeW6Punpk    194
1c04d58624    194
8lrPAakdPZ    193
8a323c1f3d    193
0dd534792b    192
ef264f7459    192
e3f9b5ae51    192
a2440ddaeb    191
76a78f4cd1    190
C7KGmBdYL5    190
b03031d32f    190
803fc75877    190
38520357f9    190
e38015ecfa    190
216c513ea6    190
2d8e6a7c30    190
1dc61a56b8    190
648984622c    190
6584e1bdba    190
793d28febc    189
61a8080306    189
ebbe892089    189
a2d402a6b3    189
ccd90588a4    189
907ebf32ae    188
7a5d2e6161    188
03ba8f1467    186
2ff9d4485e    186
7110b7b291    185
acf82046d2    184
f01476af8a    184
17aa1edd16    183
ed472df66d    183
72b39ec48a    182
6c19e6ffea    182
EXwMnX/Zun    182
ca79433bcd    182
278f971e13    181
9f1eeee836    181
f0748f4a9f    180
733d6bcc77    180
4d1c03dc29    180
5ddb941801    180
f031b848ce    180
4935382dc4    180
a95a05fb25    180
Ewt6ZQbMkN    180
c2912a65ab    180
1088d6ddd3    179
d5652591d5    179
b2e6a5dfdd    179
e4008edf1e    179
f82c98019a    179
9a729060ef    179
42f7c74041    178
ae405c0033    178
5e7a7e626c    178
546efd93e3    178
04c03768e0    177
750b9d2d43    176
e432412481    176
2853cc039e    176
e1b453beae    176
84ed4d5d2b    175
60ff7f96ca    175
18ffef9b42    175
2fbe0acf9a    175
b70562c3d0    175
3a0b9b2b88    175
7e913b3085    175
2f0624c6c9    175
d85d057526    175
62235029e4    175
c03fbd81d0    174
584431a150    174
5b4e1d509e    174
e944963fb2    173
00d3a79b20    173
6228bacd44    172
a3afb84af6    172
6681b31851    171
28886aabab    171
387672a698    171
4ec6507dc0    171
3210a28876    171
cd16392000    171
0b3f472b4d    170
2de6b28e8e    170
2b45893fa5    170
0e2c4f44a4    170
099ab8e8c3    170
0/eYPFomxx    170
89a81dbf51    170
02ba5680e8    169
943a2bc0bc    168
KcfwOao4pq    168
7ee3c7520a    168
94RlkdIJPc    167
36f9d6b201    167
fed9283130    166
e811e1e800    166
2q0YsSCxbH    165
5514f1fa33    165
25c3b77697    164
693498453f    164
4ddca7b291    164
37d8b85c2b    163
0453936d42    163
3jZNkFBl6Y    163
1ce3dbe04a    162
62c22754dc    162
dd80797654    161
a205d77611    161
a0b810febb    161
b601eb170b    161
ee5b2665ab    160
ee1827b176    160
3/2ZhYCSrj    159
97a7792b2a    159
0f8e5a877d    159
4783127847    159
a1338dccd7    159
9aa3337b53    158
41902fdda9    158
a9959a0c3b    158
d5630e30fe    157
01739d1ad7    157
6432cb46e6    157
ea63caa914    156
4d9b2590ad    156
0db5926358    156
Isi8KrDnTy    155
d2e10ca40e    155
a37bf6745c    155
cc50893153    155
f38d2f5161    154
+854AcBQT2    154
9+YvxgwXCr    154
7648c71c85    154
15a27b8894    154
1f932178fe    154
d1f514485d    154
b03c5c6089    154
2df23a10ae    154
858a95c5ca    152
37d546486f    152
f7700361e6    152
4pw2r6WOLL    152
2ce631e39e    152
0e97d0aacc    151
634253915c    151
ca513ad1df    150
0cb2f2263d    150
ae2bb23e37    150
f74be7b2cb    150
87de0a20a9    150
FiUfYp6nKO    150
DLaN/v1XdI    150
1f786b4c2b    150
bfe6aa5c86    150
9c5a13df23    150
1e798cb0dc    150
6a9e2250cb    149
3e199934c5    149
0f2cfb08cc    149
09e4083aae    149
dba7b1647f    149
54163aa028    148
0DeimCpZOc    148
62a3bdc3ae    147
4oRa9YwYR4    147
81f55fffc2    147
0e8763bdaa    147
f044b3b425    146
2PbwFG2K9y    146
f1b81b6f44    146
GQJqAknnaU    146
c789c9c1b9    146
1ca72fb06e    146
846a0ea574    146
faba0ebe0f    145
b66b4efcdc    145
7244cddabb    145
de60374173    145
IzPItEGe6F    145
a1b56e0db3    144
cd0240e31c    144
98f5843f67    144
98ed726da2    144
d47bb88460    144
0d1591cd3e    144
33afa112b8    144
a4731e780e    144
70602ce404    143
be5b308ac3    143
c0f8017596    143
2ee9e9abb7    143
e3e81301db    143
f76d889a00    143
e44ace77b5    142
c739d72d27    142
32efeeecff    142
OIN3dPhTGv    141
fd4cd26aee    140
faff946e0a    140
f80808d335    140
5bFHC1hRn8    140
8db6ad17c2    139
5RMks2Nhbt    139
3ad83fded7    138
6088c79e6e    138
606eef80b9    138
e70b79d266    138
c162ba5777    138
BrK05kZL/5    138
2f6cd52ea0    138
ae5719e1fe    137
2494060858    137
31a76e82c8    137
e03f195e9d    137
d1bad0e687    137
61aea78c0e    137
4bv77IHLBw    137
504aba9583    137
12193e3814    136
9491d704e5    136
1b835655c4    136
65de46d6fd    136
49b114a5a0    135
f6c994077c    135
FSTkdCgmAC    135
acf0862641    135
370d7dd8ee    135
350848e7fd    135
CUHgucWY5a    135
553b77a64b    134
a4bb2b81aa    134
613afb4ef6    134
855fdf0ecd    134
8273179779    134
b3f333a1d0    134
++ctND+jGD    134
10ae6c0752    134
6cf6724c34    133
Py1jxYGkim    133
b47a0101f9    133
548eee368f    132
72e3af3e66    132
db0791b8ad    132
00dde6cc1a    132
322d929b07    132
f1503855b3    132
d5e87cc762    132
5da0a0ecca    132
9dbc70e891    131
4fec989ccb    131
ETS5upSJ97    131
33e24a2f64    131
7e069ea2c0    130
0dbf0ff0ee    130
895191e055    130
/EkqCbWDau    130
9cf50c13b7    130
35gi1DzgNK    129
871ed175f0    128
d8db9d924c    128
1e55cfc9d0    128
Fm85RE1GD9    128
923c4e27ac    128
EwsD2npEpd    128
76d1b59cbf    128
675f8fc849    127
c565d3f89f    127
6e7d7d382f    127
54f06fd956    126
15bdb525ee    126
968695decc    126
V6JPgm7LAr    126
d0c1429857    126
e283688f51    125
2102ce88d7    125
ecca358713    125
GrhhfTDR3V    125
86a3978ac0    125
079520927c    124
/u0FSD+ahi    124
3a4c62d337    124
2aa04dcab7    124
7f516fe61d    124
f19af8b8d0    123
06785d5060    123
71966bb79a    123
89f6e90646    122
1296cbe30d    121
84735bd374    121
25ca80f547    121
aedcde1854    121
bb623222fe    121
59ee593a34    121
51qrsXM+vt    120
05c15d7e09    120
1479b0d550    120
4ad57373f3    120
e714526263    120
3e443899bd    120
b4f8f69157    120
5c06e43c1d    120
8d15aa75c9    120
cc2f786391    120
01a82dddd9    119
4aed6896bf    119
eee643742a    119
db511d167e    119
3fba2329f3    119
b6ac0585d9    118
4437c09247    118
5d52abb23f    118
32e83af71c    118
AJ5dgXjb+X    118
46dbc7dcd6    118
9dErPB9dKW    117
6dd4700581    117
98a7cae8a3    117
92419cabe3    116
fc94bafc0d    116
e4bff3a300    116
39137ffebc    115
3zwc9ry2i5    115
0dee62a700    115
ea85ca97d5    114
OUowUHTtLd    114
0370372c6e    114
88d3079bec    114
7e6536f0d9    114
9509525052    114
195bb1a7d0    114
0cc45ae2bc    114
db0d86e863    113
63a351808a    113
8a73b8c347    112
2e2d102a42    112
315d371664    112
APmYLwtmu5    112
72b82812b8    112
8502115f41    112
1cfb94ba00    112
2a8c5b9124    112
c1655451f8    111
ad8cc20055    111
7lzv+ATCVV    111
194a62eeca    111
c8a56cc42f    111
1e6np3yqFN    111
6ac1525c3d    111
0e2765e5c9    110
ffb86d66d2    110
1c11a2fcbb    110
f8cc619f6f    110
17f9a3b1e9    110
c81f949bae    110
94737f2f96    110
4c86d8a421    110
2cb7c0411a    109
N6IOZpKXo/    109
B5ehoKDHeD    109
f68cb03a95    109
2cce684137    109
a7bbb57eb8    109
e8e466c1ea    108
2326013eb9    108
a5886b5b03    108
/0LopuZdd7    108
1aaa7abf7d    108
959658abb9    107
7e90b35166    107
8a38743bb5    107
OyZYjyJHxf    107
db03a198b7    107
aa91e8718d    106
04a0ee1737    106
2b505c13be    106
0f0b8a3784    106
b068ba5b06    106
51e89c8052    106
b6384541e3    106
be3c23ac6e    105
e1481c6c14    105
62ec3f2cca    105
30e17fc1bd    105
31e3922211    105
8d01db6669    105
51e451fa92    105
8dfe1c8bd7    105
0750e323a9    104
9708bb99ce    104
e7d7bc04ca    103
d319c2d769    103
66bd7d67b3    103
c876ac322e    103
f514541f35    103
3f1931804e    102
6KGV6b77hq    102
d5bdd4f4cb    102
BibJ2PNHaK    102
299bd33e4e    102
4461255745    102
/MMplBlWjh    101
4bae453dd8    101
9b651aa3c1    101
5ad9682622    101
8e7dd05872    100
279ff6dd4c    100
e8f485b5f5    100
07b6df51b6    100
3cVu6QQcZ6    100
e5be78733d    100
f1c28b5184    100
decfc6ce9f    100
c95e040d91    100
8cf803be2d    100
d87c64e77e    100
103de82e6f    100
6cf2e55747    100
d842a954b3    100
CrMNjvSdA1    100
df1f148700    100
2f51ddb871    100
81eb4fbe13    100
8d793d768f    100
fc47217605    100
a04d8bb156    100
d76adbf67c    100
7934060640    100
88b395081d    100
4594a90da8     99
54a4c16599     99
a8cbf6ae52     99
6c7f70aa17     99
c5bb5bc760     99
33760a1784     98
bd96de56c7     98
37403bd2f0     98
49c6166aa4     98
e98937bf09     98
98f139c1ae     98
c2d7028869     98
LsaWR4BkIP     98
c8ac59a7e2     97
2ef4998a2c     97
28eb0bff51     97
0ce97bf245     97
084874fe51     97
01a5e73202     97
9ee6e052ba     97
df3de33bb0     97
9fdd6297cc     97
3987fc3ce3     97
2bfe22b150     96
755c970b00     96
af94e99bb3     96
7ECXh+RvQZ     96
1712c27ed4     96
607f12abc4     96
dfc6d54521     96
a76b0bbbbb     96
43214f05c4     96
61aeab8e6a     95
cf4ba4a993     95
ba7d339db9     95
JPAi4nBvwL     95
54632806b1     95
486a9ec424     95
2f60022f15     95
e02ac3afbd     94
2cf03bfed7     94
cb1a8301f6     94
e849f04f6d     94
4c6776a171     93
28e9c73cbd     93
55b8970644     93
89fe68970f     93
179dbe1fae     92
3b08bee011     92
5c7e7e1b92     92
RRF4SIW9BU     92
1a7bb35cb9     92
116bf9b603     92
3c9b706691     92
7e9ff300c0     91
292f19e337     91
ffcc507579     91
ab5049e2ec     91
3c2b2b5d1d     90
adde936e08     90
2LuHm8D2MC     90
170b6e8e1b     90
e0d5505c05     90
8c8c0ccc91     90
2b097863c5     90
bbd21e20cd     90
fe7b4330a3     90
00e7b9b504     90
26b80fd656     90
a2211187c0     90
CvUAiacu51     90
c5353fecfe     90
8eb03db9d4     89
9ddc918a99     89
21da669561     89
/0FxP3az1x     89
e84e194dc7     89
a53d5fb6b1     89
70123526e1     89
C5aZKGt6gS     89
A0Zx8a4rBD     88
eba24fcecf     88
4a8956a307     88
8JgRZeFDVZ     88
7009fc85da     88
e73916ef7e     88
00c5ee75b8     88
9f757ed330     87
44fdb0e5e4     87
665885c99c     87
d6f70d63cd     87
8c2c6590fb     87
b86a147f09     87
5fYMdwNUtL     87
10d60f7339     86
c7fc758f2c     86
d201739e7e     86
41a9a91418     86
193d2199b8     86
88A1uJBVDS     86
0TTGQF5ChH     85
3bcda1f7e9     85
43ac8042f5     85
fe70e431df     85
1437f887a3     85
50a1aa3c04     85
3aba7c72d7     84
b124cddd9c     84
c61fbcc730     84
6eaf29f53c     84
12b9783462     84
54c703f9a5     84
eae0293041     84
98f652f048     84
e67ab188d6     84
13HRN5dKgY     84
7bd4f094e9     84
6d906c6ae4     83
d468bcca31     83
M38xuj0zOC     83
4K++Px614U     83
JIT9Drf2/Z     83
92943d25d1     82
cca0b90f3b     82
HnZcTw5+Go     82
8a82e2da3f     82
361ad1d222     82
8X69F2OHjn     82
4eA1+4uyTK     82
2d74ac9bae     82
BBaYVXRKMU     81
8a2ccb6f52     81
6c44427d0d     81
c916b4fdd1     81
028f73b7fb     81
cc00b5ad92     81
a54dc1b002     81
6d81ab4bd7     81
6/1Gti3zBg     81
be43441a0e     80
4cc230692a     80
GBxcFm9Hqd     80
315129f2f8     80
ad833a769b     80
02b1c245b2     80
6e10d5bccd     80
276601755d     80
77255d2612     80
de9436437b     80
9b7d4310ff     80
facf406c21     80
e1ca03b0b4     80
81c225d41a     80
603a03131a     79
HoZ4ygxW6Z     79
+bO+qkSonO     79
cde337741a     78
7f0899ccf8     78

It looks like there are a lot of cell towers which are being used that have a lot of value. But to determine which one's to cutoff. We also need to take into account the number of users for each cell tower

In [51]:
# Let's first figure out a cutoff point for the amount of value
# For each cell tower.

In [52]:
# SMS_rate = 25sh
# Call_rate = 28sh/minute

# SMS = 8 SMSs
# Call = 2 minute * 7 = 14 minutes

# Anything above this amount would be fine
# For a cell tower over 3 days

(25 * 8) + (56 * 7)

# Anything over 600 in value
# Is ok. Cause it could be a rising cell tower.
# in population. Meaning there may be more people using it
# Over time. As the population grows.

592

We need to determine the number of times a cell tower is used

In [53]:
cell_ids_count = cell_ids_group.count()
cell_ids_count.columns = ["Count"]
cell_ids_count = cell_ids_count.sort_values(by = "Count", ascending = False)

with pd.option_context('display.max_rows', None, 'display.max_columns', None):
  print(cell_ids_count[cell_ids_count["Count"] >= 10])

            Count
cell_id
ffa6759bb2   1960
03ee801971     73
cc7ce19d6b     65
b78724d6fc     42
d22224b2fa     40
f54e480df9     40
cd828df0e4     39
e5e1285933     39
613afb4ef6     38
b4f8f69157     37
ef7d7f4e3b     36
32b36c0459     34
ab68996d93     34
42f7c74041     32
8cee3d86a3     31
dd11e50b5d     31
c916b4fdd1     30
14bedd66a9     30
5c7dc2f617     29
cc2f786391     29
55b8970644     28
19c95a8eca     28
d3877ceeca     28
1e78f22c1f     28
6f19884dcb     28
be04d38f70     28
985a02d2d5     28
367312dffd     27
0bb30f4eb8     27
7ea7f9e5ec     27
b42d04b0d7     27
3fd6b1e377     27
a04daaa926     27
cbb953ec8e     27
65de46d6fd     26
7773627c12     26
a9cf96eff4     26
0a5355b362     26
5098c9e365     25
94737f2f96     25
a7dff74777     25
c497f58c1d     25
803fc75877     25
f053be2418     25
943a2bc0bc     24
b67ec11806     24
178dc8724e     23
b7d5388b0c     23
bcc3209833     23
07ed226112     23
ea63caa914     23
5482031762     22
f8f987f764     22
8ab909c82e     22
5bcb7ce6d0     22
706d8914d0     22
ce13ed29dd     22
eb12615903     21
6f4d9b77a5     21
cf4ba4a993     21
f9639af5ac     21
7e38b2813d     21
34ac6e4be2     21
577dd249c0     21
5d9e63befc     21
3c9bd2ca37     21
885037e317     20
ebbe892089     20
f94a8ed5d0     20
2ff9d4485e     20
1712c27ed4     20
4db0540b25     19
c565d3f89f     19
3c5b7b0f2a     19
4ddca7b291     19
4f64e93674     19
4a7047f1ba     19
a78717d203     19
a8c1a2f1a7     19
687f868757     19
dec5b1f3c4     19
2f50f519d6     19
f0703eac99     19
5fb791cf56     19
7568c25ea2     19
faec238627     19
99586d686c     19
76d1b59cbf     19
4b216dac9b     18
253f3e83ab     18
437de362db     18
c2bb42ad2c     18
7a5d2e6161     18
89b82605a0     18
14f72fc8bd     18
9f847444ba     18
96593c24dd     18
de92883668     17
7145abb928     17
0b3d50be80     17
bc1d885e30     17
085e63acc5     17
62d0341dfd     17
ef264f7459     17
3003be076c     17
d1bad0e687     17
8359231c1e     17
93cf66f451     17
88425d57f4     17
4db5de545c     17
7475da2c3e     17
876704aa20     16
e3d9ef7e42     16
ae3c1f202a     16
03aed941ac     16
2cf03bfed7     16
2ed1c6a4c6     16
63285aff02     16
be3c23ac6e     16
f3aa9e7eb8     16
80c2221eec     16
4c8309ed11     16
038b1c178e     16
385e06ef74     16
4783127847     16
3ac5beb8f8     16
2bf510682b     16
0781f625a1     16
9d09fa15ee     16
4abcf1006e     16
9ede6af1ec     15
a3f835cccb     15
7475af0010     15
1e5b71aee6     15
74ffac08d2     15
6c7f70aa17     15
6e9f56b3df     15
afefb687c9     15
47yB6si0R9     15
e4c6d4fec2     15
e6d1a0e5b1     15
+pZNtCvhmT     15
db13b7dfd7     15
04b6fa5555     15
2aa04dcab7     15
32efeeecff     15
e12d87c801     15
/0FxP3az1x     15
359b6f241a     15
333a141d84     15
fb2d5cd3ff     15
01743e1656     15
c919baf9c8     14
4b39f70b40     14
5935c85c67     14
c92be6915d     14
e22b44de5a     14
cba68d0aba     14
3210a28876     14
d7cb25d4f4     14
d04adb67fe     14
a57c0c8f99     14
6381c01996     14
15f5725977     14
0c2371d9bc     14
10ae6c0752     14
b1adfda1f4     14
6b749a3b0f     14
1a7c017628     14
57ffe34d97     14
68791ae38d     14
0b3f472b4d     14
c3a6d994b3     14
c52b9b991c     14
6432cb46e6     14
fa8a209780     14
401796e91a     14
86a3978ac0     14
d13adda2d8     13
278f971e13     13
98ed726da2     13
da96896341     13
8lrPAakdPZ     13
9f2025bbed     13
93d38fc386     13
858a95c5ca     13
069b659109     13
0a01c94258     13
0a2c94daef     13
485ef0de75     13
46007ed334     13
be6853dbcc     13
25b28c826b     13
7af7f866c8     13
7e9ff300c0     13
d0b9055142     13
006b8ebb98     13
294c5de37f     13
e3ef47df3f     12
e19067447c     12
75129a301e     12
86e48eb9c2     12
fdfe4e8c70     12
8415b8e237     12
60d4453738     12
f907585c1f     12
5a7f6cf0fa     12
+38u2u/rfx     12
2e540c7097     12
5da0a0ecca     12
88b395081d     12
e28d098535     12
28ef6c4ef2     12
4a4160c38b     12
0518fc8d4e     12
da3bdb03a1     12
cf0d211307     12
a2d35deb78     12
a2d402a6b3     12
5116d1c4a6     12
a37bf6745c     12
a4bb2b81aa     12
a784b2f173     12
25c3b77697     12
06cd7ac7ac     12
0a27eecceb     12
db03a198b7     12
b6ef90bf41     12
95cd70b9ed     12
189a0fa37b     11
1bbd2d834d     11
/eeMklgyJA     11
6fddc7c18f     11
2e93a4410e     11
634253915c     11
49b114a5a0     11
2b2707d319     11
176sGHv7Ym     11
c789c9c1b9     11
46b9480a4b     11
ae00876856     11
a6606f4ac1     11
63711883f9     11
4cb70ebae5     11
4261f660ef     11
fc28d26e2d     11
2d5e6a3639     11
819fb474a6     11
e0532725f2     11
629f49257b     11
2901cbe78c     11
92a4a0642c     11
5RMks2Nhbt     11
e02ac3afbd     11
0nabagle1r     11
0ff4f68649     11
287bb1c957     11
117024cabb     11
5b4e1d509e     11
5b975beadf     11
97a7792b2a     11
98f5843f67     11
54Pb8dz/52     11
d85d057526     11
d1f514485d     11
ea23bd588b     11
31a76e82c8     11
871ed175f0     11
54163aa028     11
534bf6a254     11
5139351fad     11
216c513ea6     11
60339d459f     11
d03cc00eff     11
4eA1+4uyTK     11
593ccf9394     11
0MZBLLzPYZ     11
1a753bd760     10
69PzMuWJR2     10
88c34bb286     10
64138404ce     10
5pIl0RaDmd     10
5d9dc897f7     10
1dc61a56b8     10
1f786b4c2b     10
5475c0798b     10
504aba9583     10
4oRa9YwYR4     10
439f07c2ce     10
3IoIGy1+o8     10
37144b64f7     10
301gn/BrU5     10
2ee9e9abb7     10
18iJZATMMC     10
2aXXOLyR5M     10
18ba0c44e5     10
079520927c     10
7b43d3cd70     10
7d370f006d     10
e21c9c8e36     10
af9dce19ee     10
0Fmr/IZtQ+     10
dd98a379f0     10
db0d86e863     10
d8db9d924c     10
9cfc878d60     10
b3f333a1d0     10
14407a3d56     10
8418cc64dd     10
d5652591d5     10
8bea4b4e6c     10
c03fbd81d0     10
87cef82479     10
cc50ee0fc9     10
05813ba0f9     10
cc50893153     10
eb962cac28     10
7OeLONGBwT     10
ae4db80773     10
f76d889a00     10
7244cddabb     10
+854AcBQT2     10
9fdd6297cc     10
729b6b4b22     10
BibJ2PNHaK     10
+ZaaZozy/+     10
77XAFQmoad     10
94438769e6     10
LfzZVh+YOT     10
74fe8b33ec     10
f0b2be0842     10
0/eYPFomxx     10
765d191617     10
a394529de6     10
a5e351b2b3     10
c162ba5777     10

A good number looks like 15. For expansion

Now we can decide on the value and amount of users to look for.

1. Join the tables

In [54]:
cell_ids_join = cell_ids_values.join(cell_ids_count)
cell_ids_join

            value  Count
cell_id
ffa6759bb2  15284   1960
2def69183e  12900      1
3f5ac97214   6800      2
MpOhP3OKNN   4225      7
5a7f6cf0fa   3437     12
...           ...    ...
893374a632      0      1
c64aa83e02      0      7
2cbeafa5ec      0      1
8902485338      0      3
49906a2896      0      1

[2677 rows x 2 columns]

In [60]:
# Check if any are null
cell_ids_join.isnull().sum()

value    0
Count    0
dtype: int64

In [56]:
# None are null

2. Searches

In [57]:
search_results = cell_ids_join[(cell_ids_join["value"] > 600) & (cell_ids_join["Count"] > 15)]
search_results

            value  Count
cell_id
ffa6759bb2  15284   1960
89b82605a0   1823     18
19c95a8eca   1780     28
07ed226112   1288     23
d22224b2fa   1281     40
cd828df0e4   1265     39
a9cf96eff4   1121     26
3c9bd2ca37   1082     21
7ea7f9e5ec   1055     27
ab68996d93    956     34
32b36c0459    853     34
5482031762    848     22
706d8914d0    789     22
885037e317    786     20
687f868757    785     19
b7d5388b0c    782     23
577dd249c0    757     21
bc1d885e30    733     17
4db0540b25    729     19
876704aa20    725     16
bcc3209833    687     23
b42d04b0d7    687     27
e5e1285933    662     39
4abcf1006e    641     16
6f4d9b77a5    638     21
de92883668    634     17
c497f58c1d    610     25

In [58]:
len(search_results)

27

### Evaluation

In [59]:
# This means that we have a list of 27 areas
# Where we can increase the number of cell towers.
# However the first one can be ommited. Because it contains a lot of
# traffic and appears to be just in a busy area. If they want to reduce the load
# They can add another tower. However maybe that area is already too populated. And not
# many more people are going to be there.